<a href="https://colab.research.google.com/github/abhijeet-0019/deep-learning-practice/blob/main/CNN01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPool2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Flatten



*   mnist is the dataset of images
*   sequential is the way to build the models

*   conv2d, as we are dealing with 2d images


other usages in the data below

In [ ]:
# here we are loading the data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
# here we are reshaping the data
X_train = X_train.reshape((X_train.shape[0]), X_train.shape[1], X_train.shape[2],1)
X_test = X_test.reshape((X_test.shape[0]), X_test.shape[1], X_test.shape[2],1)

In [ ]:
# here we are checking teh shape after reshaping
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [ ]:
# noramlizing the pixel valules
X_train = X_train/255
X_test = X_test/255

In [ ]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [ ]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [ ]:
# data is ready
model = Sequential()

In [ ]:
model.add(Conv2D(32, (3,3), activation = 'relu', input_shape=(28, 28, 1)))

In [ ]:
model.add(MaxPool2D(2, 2))

In [ ]:
# adding fully connected layer
model.add(Flatten()) #connection between convolution and dense layer, 2-D images to 1D array
model.add(Dense(100, activation="relu")) # dense is the outer layer

In [ ]:
# adding output layer (on more)
model.add(Dense(10, activation = 'softmax'))

In [ ]:
# compiling the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fitting the model
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 39s 20ms/step - loss: 1.2522 - accuracy: 0.5783
Epoch 2/10
1875/1875 [==============================] - 34s 18ms/step - loss: 0.7483 - accuracy: 0.6033
Epoch 3/10
1875/1875 [==============================] - 36s 19ms/step - loss: 0.6024 - accuracy: 0.6894
Epoch 4/10
1875/1875 [==============================] - 34s 18ms/step - loss: 0.4078 - accuracy: 0.8253
Epoch 5/10
1875/1875 [==============================] - 35s 18ms/step - loss: 0.2331 - accuracy: 0.9824
Epoch 6/10
1875/1875 [==============================] - 35s 18ms/step - loss: 0.1225 - accuracy: 0.9920
Epoch 7/10
1875/1875 [==============================] - 34s 18ms/step - loss: 0.0809 - accuracy: 0.9929
Epoch 8/10
1875/1875 [==============================] - 34s 18ms/step - loss: 0.0538 - accuracy: 0.9949
Epoch 9/10
1875/1875 [==============================] - 35s 18ms/step - loss: 0.0431 - accuracy: 0.9951
Epoch 10/10
1875/1875 [==============================] - 34s 18m

**Accuracy of the Model**

In [ ]:
# evaluating the model
model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 7ms/step - loss: 0.0723 - accuracy: 0.9854


[0.07231569290161133, 0.9854000210762024]

**THIS IS THE *CNN* MODEL**